title: "Muntashir Al-Islam"
tagline: "About"
author: "Muntashir Al-Islam"
description: "Muntashir Al-Islam's whereabouts"
email: "muntashirakon@riseup.net"
twitter:
  username: "Muntashir"
social:
  name: "Muntashir Al-Islam"
  links:
    - https://twitter.com/Muntashir
    - https://github.com/MuntashirAkon

plugins:
  - jekyll-seo-tag

# exclude
exclude: ["CNAME", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
